version: "3.9"
networks:
  grafana_net:
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - grafana_net
  mysql:
    image: mariadb:10.6
    container_name: mysql_base
    restart: unless-stopped
    tty: true
    ports:
      - 33064:3306
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_USER: jik
      MYSQL_PASSWORD: 1122
      MYSQL_ROOT_PASSWORD: 1122
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - grafana_net
