{
 "title": "movie limit 3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jumlah Film",
   "type": "stat",
   "description": "Jumlah Film Pada Database",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*) from movies;\n", "selectedFormat": 4 }
   ]
  },
  {
   "title": "Presentase Pangsa Pasar Per Kategori",
   "type": "piechart",
   "description": "market share",
   "gridPos": { "h": 20, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "-- MARKET SHARE\nWITH MOVIE_WITH_CAT AS (\n    SELECT\n        movieId,\n        title,\n        genres,\n        splitByString('|', assumeNotNull(genres)) as categories\n    from\n        movies\n),\nCATEGORIES AS (\n    SELECT\n        groupUniqArrayArray(categories) AS unique_category\n    FROM\n        MOVIE_WITH_CAT\n)\nSELECT\n    categories as kategori,\n    count(categories) as jumlah\nfrom\n    MOVIE_WITH_CAT array\n    join categories\ngroup by\n    categories\n    ",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Jumlah Film Per Dekade",
   "type": "trend",
   "description": "Jumlah Film Per Dekade",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "-- belajar\nwith MOVIE_WITH_DECADE AS (\n    select\n        movieId,\n        title,\n        toInt64OrZero(\n            concat(\n                toString(\n                    intDiv(\n                        toInt64OrZero(\n                            replace(\n                                replace(\n                                    splitByWhitespace(assumeNotNull(title)) [-1],\n                                    '(',\n                                    ''\n                                ),\n                                ')',\n                                ''\n                            )\n                        ),\n                        10\n                    )\n                ),\n                '0'\n            )\n        ) as decade\n    from\n        movies\n    where\n        decade != 0\n)\nSELECT\n    decade,\n    count(*) as jumlah_film\nFROM\n    MOVIE_WITH_DECADE\nGROUP BY\n    decade\nORDER BY decade",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Top 10 Movies All of the times",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "-- IMDB SCORE\nWITH MOVIES_RATING AS (\n    SELECT\n        r.userId,\n        r.rating,\n        m.movieId AS movieId,\n        m.title,\n        m.genres\n    FROM\n        ratings r\n        INNER JOIN movies m ON r.movieId = m.movieId\n),\nRATING_MEAN AS (\n    SELECT\n        AVG(rating) as rating_avg\n    from\n        MOVIES_RATING\n    group by\n        movieId\n),\nTOP_TEN AS (\n    SELECT\n        title,\n        count(userId) as num_votes,\n        -- v --\n        avg(rating) as rating_mean,\n        -- R --\n        (\n            select\n                AVG(rating_avg)\n            from\n                RATING_MEAN\n        ) as C,\n        (num_votes /(num_votes + 346.0) * rating_mean) + (346.0 /(num_votes + 346.0) * C) as score\n    FROM\n        MOVIES_RATING\n    GROUP BY\n        movieId,\n        title\n    ORDER BY\n        score DESC\n    LIMIT\n        10\n)\nSELECT title, num_votes, score FROM TOP_TEN",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Jumlah FIlm Per Kategori",
   "type": "barchart",
   "description": "Jumlah Film Per Kategori",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH MOVIE_WITH_CAT AS (\n    SELECT\n        movieId,\n        title,\n        genres,\n        splitByString('|', assumeNotNull(genres)) as categories\n    from\n        movies\n),\nCATEGORIES AS (\n    SELECT\n        groupUniqArrayArray(categories) AS unique_category\n    FROM\n        MOVIE_WITH_CAT\n)\nSELECT\n    categories as kategori,\n    count(categories) as jumlah\nfrom\n    MOVIE_WITH_CAT array\n    join categories\ngroup by\n    categories",
     "selectedFormat": 4
    }
   ]
  }
 ]
}